### PR TITLE
[Fix] Correct bug in editing across DST boundaries

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by tkellen** [comment]
date math in javascript is biting everyone this week!

**Comment by tkellen** [comment]
I haven't run this change-set locally, but :+1: for letting moment handle this entirely. Let's :shipit:.

**Comment by tkellen** [comment]
Confirmed locally this is good.

**Comment by jugglinmike** [comment]
Thanks, Tyler!

**Pull request merged**
