### PR TITLE
[Fix] Reset "billable" flag between navigations

### PR DESCRIPTION
**Pull request by jugglinmike**
When the underlying utilization changes for a given day, ensure that the
"billable" value is updated accordingly.

@tkellen Mind giving this a once-over?

Resolves gh-126

### CODE REVIEW

**Comment by tkellen** [comment]
Doing so now.

**Comment by tkellen** [comment]
Looks pretty straightforward. Was this issue present with the previous implementation?

**Comment by jugglinmike** [comment]
All signs point to "yes."

**Comment by tkellen** [comment]
Super confused how that could be the case--it would have greatly skewed our billable/non-billable counts in Admiralty and we rely on those heavily for knowing when we've completed delivery of an SOW. Thanks for putting this together @jugglinmike!

**Comment by jugglinmike** [comment]
This bug was only evident when navigating between weeks in the same phase. The general workflow is to verify a single week per review session. In that case, navigation is primarily between that one week across phases.

The unrelated bugs surfaced by the change into daylight savings time caused delays in the review process, and ultmately forced you guys to review multiple weeks at once.

My guess is the atypical workflow, combined with [the more prominent presentation of the "billable" attribute](https://github.com/bocoup/nest-weekly-review/commit/cea972345596cdd4f478a3faed263973431efb32), made this bug especially apparent.

**Comment by tkellen** [comment]
That actually makes perfect sense. That also accounts for the two or three times where things went askew and we were unable to determine the root cause to submit a bug report. Thanks @jugglinmike! Also, I just deployed this.

**Comment by jugglinmike** [comment]
https://www.google.com/#q=askew

**Comment by tkellen** [comment]
aughh! lol

**Comment by tkellen** [comment]
PS: It hasn't escaped me that I introduced this bug. Sorry!

**Comment by jugglinmike** [comment]
It escaped *me* until you pointed it out. Now I am plotting ways I can sneak a back door into the Nest API.

**Pull request merged**
