### PR TITLE
correctly persist leave_request_type_id when it is null

### PR DESCRIPTION
**Pull request by tkellen**
closes gh-129

### CODE REVIEW

**Comment by tkellen** [comment]
I wish I understood more clearly *why* this works, but it works.

**Comment by jugglinmike** [comment]
> I wish I understood more clearly why this works, but it works.

For Leave Request Types, `null` is an acceptable "new" value and should *not* prompt the UI to substitute the "old" (pre-editing) value.

**Comment by jugglinmike** [comment]
I added a test to prove this fix. Deploying shortly

**Comment by jugglinmike** [comment]
@tkellen The fix has been deployed. Can you confirm it is working as expected in production?

**Comment by jugglinmike** [comment]
Annoyed that the build is failing because TravisCI can no longer resolve the reference for the merge. Maybe annoyed enough to push an empty commit to `master`.

**Comment by tkellen** [comment]
Thanks @jugglinmike! This is working correctly now.

**Pull request merged**
