### PR TITLE
Introduce "Leave Request Types"

### PR DESCRIPTION
**Pull request by jugglinmike**
This inserts another field into each utilization UI element, further weakening any visual hierarchy we'd like to enforce there:

screenshot from 2015-11-10 14 45 03

Trying to make the most of a difficult situation, I've modified the presentation of the utilizations themselves. The "billable" attribute is now a more abstract "dollar sign" glyph rendered behind the existing text. This opened up some vertical space, just enough to add tiny labels for each attribute:

screenshot from 2015-11-10 14 45 18

I'm hoping this makes it slightly easier to understand the state of a given utilization.

Resolves gh-120

### CODE REVIEW

**Comment by tkellen** [comment]
reviewing now

**Comment by tkellen** [comment]
:+1: from me with one minor request: could we hide leave request type entirely if it's missing?

**Comment by jugglinmike** [comment]
@tkellen Sure. I'd like to render the empty space in order to promote a horizontal grid. Does that sound okay to you?

**Comment by tkellen** [comment]
:+1:

**Comment by jugglinmike** [comment]
Having an issue with tests (what else is new); I'll follow up with this tomorrow!

**Comment by tkellen** [comment]
Roger that. I'm gonna rebase the infra PR tonight and start on it tomorrow

**Comment by jugglinmike** [comment]
Rebased and merged to `master`:

- 47bee73921f17e143df1fede81a7b103e6aa58a2
- 6af345c7cf514e2079a722e6a2e8ebde13518578
- cea972345596cdd4f478a3faed263973431efb32

Thanks for the review, Tyler!

**Pull request closed without merging**
